Modules/Profile/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth'])->group(function() {
    Route::get('/blocked', 'PersonalProfileController@blockedShow')->name('blockedProfile');

    Route::get('/my_profile', 'PersonalProfileController@show', ['name' => 'my_profile'])->name('my_profile');
//    Route::get('/my_profile/edit', 'PersonalProfileController@edit')->name('my_profile.edit');
//    Route::put('/my_profile/update', 'PersonalProfileController@update')->name('my_profile.update');

    Route::resource('/tags', 'TagController', ['name' => 'tags'])->middleware('permission:profile-tags-edit');

    // Roles
    Route::resource('/roles', 'RoleController', ['name' => 'roles'])->middleware('permission:profile-roles-edit');
});

//Route::resource('/profile', 'ProfileController', ['name' => 'profile']);
//todo сделать нормальную страницу с выводом интересных профилей
Route::get('/profile', 'ProfileController@index')->name('profile.index');
Route::get('/profile/{profile}', 'ProfileController@show')->name('profile.show');

Route::middleware(['auth'])->group(function() {
    Route::get('/profile/create', 'ProfileController@create')->name('profile.create')->middleware('permission:profile-edit');
    Route::post('/profile', 'ProfileController@store')->name('profile.store')->middleware('permission:profile-edit');

    Route::get('/profile/{profile}/edit', 'ProfileController@edit')->name('profile.edit')->middleware('permission:profile-edit,profile');
    Route::put('/profile/{profile}', 'ProfileController@update')->name('profile.update')->middleware('permission:profile-edit,profile');

    Route::post('/profile/{profile}/block', 'ProfileController@block')->name('profile.block')->middleware('permission:profile-block');
    Route::delete('/profile/{profile}', 'ProfileController@destroy')->name('profile.destroy')->middleware('permission:profile-delete');
});

Modules/Profile/Entities/Role.php
<?php

namespace Modules\Profile\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Role extends Model
{
    protected $table = 'profile_roles';
    protected $fillable = ['name'];

    /**
     * Проверка имеет ли пользователь определенную роль
     * @param $check
     * @return boolean
     */
    public function hasPermission($check)
    {
        return in_array($check, array_pluck($this->permissions->toArray(), 'name'));
    }

    /**
     * Получает название права
     * @param $name
     * @return mixed
     */
    public function getPermissionDisplayName($name)
    {
        return DB::table('profile_permissions')->where('name', $name)->first()->display_name;
    }

    /**
     * Функция для получение прав.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function permissions()
    {
        return $this->belongsToMany(Permission::class, 'profile_permission_role', 'role_id', 'permission_id');
    }
}

Modules/Profile/Http/Controllers/RoleController.php
<?php

namespace Modules\Profile\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Modules\Profile\Entities\Permission;
use Modules\Profile\Entities\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        return view('profile::roles.index', [
            'roles' => Role::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        return view('profile::roles.create');
    }

    /**
     * Store a newly created resource in storage.
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        Role::create($request->except('_token'));

        return redirect()->route('roles.index');
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show()
    {
        return view('profile::roles.show');
    }

    /**
     * Show the form for editing the specified resource.
     * @param Role $role
     * @return Response
     */
    public function edit(Role $role)
    {
        return view('profile::roles.edit', [
            'role' => $role,
            'permissions' => Permission::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     * @param  Request $request
     * @param Role $role
     * @return Response
     */
    public function update(Request $request, Role $role)
    {
        $role->update($request->all());
        $role->permissions()->detach();
        $role->permissions()->attach($request->permissions, []);

        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     * @param Role $role
     * @return Response
     * @throws \Exception
     */
    public function destroy(Role $role)
    {
        $role->delete();

        return redirect()->route('roles.index');
    }
}

Modules/Profile/Resources/views/roles/create.blade.php
@extends('layouts.app')


@section('content')
<h1>Добавляем новую роль</h1>
{!! Form::open(['route' => ['roles.store']]) !!}
    <div class="form-group">
        {{ Form::label('name', 'Имя роли') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
    <button role="submit">Добавить роль</button>
{!! Form::close() !!}
@stop

Modules/Profile/Resources/views/roles/edit.blade.php
@extends('layouts.app')


@section('content')
    <h1>Добавляем новый тег</h1>
    {!! Form::open(['route' => ['roles.update', $role->id], 'method' => 'put']) !!}
    <div class="form-group">
        {{ Form::label('name', 'Название группы пользователей (роли)') }}
        {{ Form::text('name', $role->name, ['class' => 'form-control']) }}
    </div>
    <div class="form-group">
        <p>(заглавными буквами выделены группы прав. они отвечают за отображение пункта в меню)</p>
        @foreach($permissions as $permission)
        <div
                @if($permission->parent_id !== 0)class="ml-5"@endif
                @if(!in_array($permission->name, array_pluck($role->permissions->toArray(), 'name')))
                    style="color:#ff0000"
                @else
                    style="color:#1ab814"
                @endif()
        >
            {{ Form::checkbox("permissions[$permission->name]", $permission->id, in_array($permission->name, array_pluck($role->permissions->toArray(), 'name'))) }}
            {{ Form::label("permissions[$permission->name]", $permission->name . " ($permission->display_name)") }}
        </div>
        <br>
        @endforeach
    </div>
    <button role="submit">Сохранить</button>
    {!! Form::close() !!}
@stop

Modules/Profile/Resources/views/roles/editPermissions.blade.php
@extends('layouts.app')


@section('content')
    <h1>Добавляем новую роль</h1>
    {!! Form::open(['route' => ['roles.store']]) !!}
    <div class="form-group">
        {{ Form::label('name', 'Имя роли') }}
        {{ Form::text('name', null, ['class' => 'form-control']) }}
    </div>
    <button role="submit">Добавить роль</button>
    {!! Form::close() !!}
@stop

Modules/Profile/Resources/views/roles/index.blade.php
@extends('layouts.app')


@section('content')
    <h1>Список доступных ролей</h1>
    <a href="{{ route('roles.create') }}">
        <button class="btn btn-outline-primary">Добавить роль</button>
    </a>

    <table class="table-bordered w-100 mt-3">
        <tr>
            <td class="p-2">
                Роль
            </td>
            <td class="p-2">
                Действия
            </td>
        </tr>
    @foreach($roles as $role)
        <tr>
            <td class="p-2">
                <a href="{{ route('roles.edit', $role) }}">
                    {{ $role->name }}
                </a>
            </td>
            <td class="p-2">
                <form class="list-inline-item" action="{{route('roles.destroy', $role)}}" onsubmit="if(confirm('Удалить?')){ return true } else{ return false }" method="post">
                    <input type="hidden" name="_method" value="delete">
                    {{ csrf_field() }}
                    <button type="submit" class="btn btn-outline-primary"><i class="fa fa-trash-o"></i></button>
                </form>
            </td>
        </tr>
    @endforeach
    </table>
@stop